from pathlib import Path
from typing import Any, Protocol


class ArtifactStorage(Protocol):
    def document_dir(self, document_id: str) -> Path: ...
    def ensure_document_dirs(self, document_id: str) -> Path: ...
    def source_path(self, document_id: str, extension: str | None = None) -> Path: ...
    def artifact_path(self, document_id: str, relative_path: str) -> Path: ...
    async def write_json(
        self, document_id: str, relative_path: str, payload: dict[str, Any]
    ) -> Path: ...
    async def read_json(
        self, document_id: str, relative_path: str
    ) -> dict[str, Any]: ...
    async def write_text(
        self, document_id: str, relative_path: str, content: str
    ) -> Path: ...
    async def write_bytes(
        self, document_id: str, relative_path: str, content: bytes
    ) -> Path: ...
    def exists(self, document_id: str, relative_path: str) -> bool: ...
    async def delete_artifact(self, document_id: str, relative_path: str) -> None: ...
    async def delete_prefix(self, document_id: str, relative_prefix: str) -> None: ...
    async def delete_document(self, document_id: str) -> None: ...
